apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        resources:
          limits:
            memory: "1024Mi"
            cpu: "400m"
          requests:
              cpu: "200m"
              memory: "256Mi"
        env:
          - name: POSTGRES_DB
            value: demo
          - name: POSTGRES_USER
            value: demo
          - name: POSTGRES_PASSWORD
            value: demo
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
            subPath: postgres
      volumes:
        - name: postgrs-data
          persistentVolumeClaim:
            claimName: pvc-postgres
