apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conv-api
  template:
    metadata:
      labels:
        app: conv-api
    spec:
      containers:
        - name: conv-api
          image: antonlarichev/conv-api:1.0
          ports:
            - containerPort: 3000
          env:
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: AMQP_USER
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: AMQP_PASSWORD
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: AMQP_EXCHANGE
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: AMQP_HOSTNAME
          envFrom:
            - secretRef:
                name: seeduser-secret
          volumeMounts:
            - name: uploads
              mountPath: /opt/app/uploads
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"    
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: conv-api-pvc 